import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { Inter } from 'next/font/google'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram,} from 'react-icons/ai';
import {IoMdConstruct,} from 'react-icons/io';
import Image from "next/image";
import deved from "../public/Capture.png";
import design from "../public/design.png";
import couteau from "../public/couteau.png";
import {useState} from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>MEPLOND - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-logo dark:text-white">MEPLOND</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill  onClick={() => setDarkMode(!darkMode)} className="cursor-pointer dark:text-white"/>
              </li>
              <li><a href="#" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>LogIn</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>Meplond Victor</h2>
            <h3 className='dark:text-white text-2xl py-2 md:text-3xl'>Artist</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-300 md:text-xl max-w-lg mx-auto'>Actuellement en études supérieurs</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mb-20 overflow-hidden md:h-96 md:w-96'>
            <Image alt="meplong-image" src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-r from-cyan-500 to-teal-500">
            <h3 className='text-3xl py-10 text-center text-teal-600 font-medium dark:text-white'>A propos de moi</h3>
              <p className="py-2 dark:text-gray-300">
                Creating elegant designs suited for your needs following core
                design theory.Creating elegant designs suited for your needs following core
                design theory.Creating elegant designs suited for your needs following core
                design theory.Creating elegant designs suited for your needs following core
                design theory.Creating elegant designs suited for your needs following core
                design theory.Creating elegant designs suited for your needs following core
                design theory.
              </p>

            </div>

          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-center text-3xl py-1 dark:text-white">Mes créations</h3>

          </div>
          <div className="flex items-center flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            <Image className="rounded-lg object-cover" alt="meuble1" src={couteau} />
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
